<?php

namespace AppBundle\Repository;


/**
 * BookingTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingTicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function nbBookingPerDate($date)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b)')
            ->where('b.bookingDate = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult();

    }
}
