<?php

namespace AppBundle\Repository;

/**
 * TTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
